"""
Composio actions — Slack alert + GitHub issue.
Uses the new Composio SDK (composio package, session-based).

Setup (one-time, before running):
  1. pip install composio
  2. Set COMPOSIO_API_KEY=ak_Pv532zVAVQJoFTReaSgt in .env
  3. Connect GitHub: composio add github   (opens OAuth in browser)
  4. Connect Slack:  composio add slack    (opens OAuth in browser)
"""

import os
import json
import hashlib
from composio import Composio
from dotenv import load_dotenv
from utils.snowflake_conn import run_dml, run_query

load_dotenv()

# Fixed user ID for this agent — must match the user that authenticated
# GitHub and Slack in the Composio dashboard
COMPOSIO_USER_ID = "incidentdna-agent"

_client: Composio | None = None


def _get_client() -> Composio:
    global _client
    if _client is None:
        _client = Composio(api_key=os.getenv("COMPOSIO_API_KEY"))
    return _client


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _idempotency_key(action_type: str, event_id: str) -> str:
    return hashlib.sha256(f"{action_type}:{event_id}".encode()).hexdigest()[:32]


def _record_action(event_id: str, action_type: str, key: str, payload: dict) -> None:
    run_dml(
        """INSERT INTO AI.ACTIONS
               (event_id, action_type, idempotency_key, payload, status)
           VALUES (%s, %s, %s, PARSE_JSON(%s), 'PENDING')""",
        (event_id, action_type, key, json.dumps(payload)),
    )


def _update_status(key: str, status: str) -> None:
    run_dml(
        "UPDATE AI.ACTIONS SET status = %s WHERE idempotency_key = %s",
        (status, key),
    )


def _already_sent(key: str) -> str | None:
    rows = run_query(
        "SELECT status FROM AI.ACTIONS WHERE idempotency_key = %s", (key,)
    )
    return rows[0]["STATUS"] if rows else None


# ---------------------------------------------------------------------------
# Public actions
# ---------------------------------------------------------------------------

def post_slack_alert(
    event_id: str,
    service: str,
    severity: str,
    root_cause: str,
) -> str:
    """
    Post a Slack incident alert via Composio.
    Idempotent — safe to call multiple times for the same event.
    Returns: 'SENT' | 'SKIPPED_DUPLICATE (...)' | 'FAILED: ...'
    """
    key = _idempotency_key("SLACK_ALERT", event_id)
    prev = _already_sent(key)
    if prev:
        return f"SKIPPED_DUPLICATE (previous: {prev})"

    severity_emoji = {"P1": "🚨", "P2": "⚠️", "P3": "ℹ️"}.get(severity, "🔔")
    message = (
        f"{severity_emoji} *[{severity}] IncidentDNA Alert*\n"
        f"*Service:* {service}\n"
        f"*Root cause:* {root_cause}\n"
        f"*Event ID:* `{event_id}`\n"
        f"_Autonomous response in progress…_"
    )
    channel = os.getenv("SLACK_CHANNEL", "#incidents")
    payload = {"channel": channel, "text": message}

    _record_action(event_id, "SLACK_ALERT", key, payload)
    try:
        _get_client().tools.execute(
            "SLACKBOT_CHAT_POST_MESSAGE",
            payload,
            user_id=COMPOSIO_USER_ID,
        )
        _update_status(key, "SENT")
        return "SENT"
    except Exception as e:
        _update_status(key, "FAILED")
        return f"FAILED: {e}"


def create_github_issue(
    event_id: str,
    service: str,
    severity: str,
    root_cause: str,
    fix: str,
) -> str:
    """
    Create a GitHub issue via Composio.
    Idempotent — safe to call multiple times for the same event.
    Returns: 'SENT' | 'SKIPPED_DUPLICATE (...)' | 'FAILED: ...'
    """
    key = _idempotency_key("GITHUB_ISSUE", event_id)
    prev = _already_sent(key)
    if prev:
        return f"SKIPPED_DUPLICATE (previous: {prev})"

    repo = os.getenv("GITHUB_REPO", "")
    owner, repo_name = (repo.split("/") + [""])[:2]  # split "owner/repo"

    title = f"[{severity}] {service} — {root_cause[:70]}"
    body = f"""## IncidentDNA — Automated Incident Report

| Field | Value |
|-------|-------|
| **Event ID** | `{event_id}` |
| **Service** | {service} |
| **Severity** | {severity} |

### Root Cause
{root_cause}

### Recommended Fix
{fix}

### Resolution Checklist
- [ ] Root cause confirmed by on-call engineer
- [ ] Fix applied
- [ ] Service health restored
- [ ] Post-mortem scheduled

---
*Auto-generated by IncidentDNA. Do not close until resolution is confirmed.*
"""
    payload = {"owner": owner, "repo": repo_name, "title": title, "body": body}

    _record_action(event_id, "GITHUB_ISSUE", key, payload)
    try:
        _get_client().tools.execute(
            "GITHUB_CREATE_AN_ISSUE",
            payload,
            user_id=COMPOSIO_USER_ID,
        )
        _update_status(key, "SENT")
        return "SENT"
    except Exception as e:
        _update_status(key, "FAILED")
        return f"FAILED: {e}"
