import os
import json
import hashlib
from dotenv import load_dotenv
from utils.snowflake_conn import run_dml, run_query

load_dotenv()

# ---------------------------------------------------------------------------
# Composio client — imported lazily so the module loads even without the key
# ---------------------------------------------------------------------------
_toolset = None


def _get_toolset():
    global _toolset
    if _toolset is None:
        from composio_crewai import ComposioToolSet
        _toolset = ComposioToolSet(api_key=os.getenv("COMPOSIO_API_KEY"))
    return _toolset


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------
def _idempotency_key(action_type: str, event_id: str) -> str:
    return hashlib.sha256(f"{action_type}:{event_id}".encode()).hexdigest()[:32]


def _record_action(event_id: str, action_type: str, key: str, payload: dict) -> None:
    run_dml(
        """INSERT INTO AI.ACTIONS
               (event_id, action_type, idempotency_key, payload, status)
           VALUES (%s, %s, %s, PARSE_JSON(%s), 'PENDING')""",
        (event_id, action_type, key, json.dumps(payload)),
    )


def _update_status(key: str, status: str) -> None:
    run_dml(
        "UPDATE AI.ACTIONS SET status = %s WHERE idempotency_key = %s",
        (status, key),
    )


def _already_sent(key: str) -> str | None:
    rows = run_query(
        "SELECT status FROM AI.ACTIONS WHERE idempotency_key = %s", (key,)
    )
    return rows[0]["STATUS"] if rows else None


# ---------------------------------------------------------------------------
# Public actions
# ---------------------------------------------------------------------------
def post_slack_alert(
    event_id: str,
    service: str,
    severity: str,
    root_cause: str,
) -> str:
    """
    Post a Slack incident alert via Composio.
    Idempotent — safe to call multiple times for the same event.
    Returns: 'SENT' | 'SKIPPED_DUPLICATE (...)' | 'FAILED: ...'
    """
    key = _idempotency_key("SLACK_ALERT", event_id)
    prev = _already_sent(key)
    if prev:
        return f"SKIPPED_DUPLICATE (previous: {prev})"

    severity_emoji = {"P1": "🚨", "P2": "⚠️", "P3": "ℹ️"}.get(severity, "🔔")
    message = (
        f"{severity_emoji} *[{severity}] IncidentDNA Alert*\n"
        f"*Service:* {service}\n"
        f"*Root cause:* {root_cause}\n"
        f"*Event ID:* `{event_id}`\n"
        f"_Autonomous response in progress…_"
    )
    payload = {
        "channel": os.getenv("SLACK_CHANNEL", "#incidents"),
        "text": message,
    }

    _record_action(event_id, "SLACK_ALERT", key, payload)
    try:
        from composio_crewai import Action
        _get_toolset().execute_action(
            action=Action.SLACKBOT_CHAT_POST_MESSAGE,
            params=payload,
        )
        _update_status(key, "SENT")
        return "SENT"
    except Exception as e:
        _update_status(key, "FAILED")
        return f"FAILED: {e}"


def create_github_issue(
    event_id: str,
    service: str,
    severity: str,
    root_cause: str,
    fix: str,
) -> str:
    """
    Create a GitHub issue via Composio.
    Idempotent — safe to call multiple times for the same event.
    Returns: 'SENT' | 'SKIPPED_DUPLICATE (...)' | 'FAILED: ...'
    """
    key = _idempotency_key("GITHUB_ISSUE", event_id)
    prev = _already_sent(key)
    if prev:
        return f"SKIPPED_DUPLICATE (previous: {prev})"

    title = f"[{severity}] {service} — {root_cause[:70]}"
    body = f"""## IncidentDNA — Automated Incident Report

| Field | Value |
|-------|-------|
| **Event ID** | `{event_id}` |
| **Service** | {service} |
| **Severity** | {severity} |

### Root Cause
{root_cause}

### Recommended Fix
{fix}

### Resolution Checklist
- [ ] Root cause confirmed by on-call engineer
- [ ] Fix applied
- [ ] Service health restored
- [ ] Post-mortem scheduled

---
*Auto-generated by IncidentDNA. Do not close until resolution is confirmed.*
"""
    payload = {
        "repo": os.getenv("GITHUB_REPO", ""),
        "title": title,
        "body": body,
    }

    _record_action(event_id, "GITHUB_ISSUE", key, payload)
    try:
        from composio_crewai import Action
        _get_toolset().execute_action(
            action=Action.GITHUB_CREATE_AN_ISSUE,
            params=payload,
        )
        _update_status(key, "SENT")
        return "SENT"
    except Exception as e:
        _update_status(key, "FAILED")
        return f"FAILED: {e}"
